name: resnet50
model_type: ResNet
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  name: cifar100
  data_type: CiFar100
  train:
    root: './data/datasets/cifar100'
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    gt_size: 224
    data_type: 'Train'

  val:
    root: './data/datasets/cifar100'
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    gt_size: 224
    data_type: 'Test'

#network structures
backbone:
  model_cfg:
    block: 'Bottleneck'
    block_num: [3, 4, 6, 3]
    num_classes: 100
    include_top: True
    groups: 1
    width_per_group: 64
  ckpt_path: './models/pretrained/cnns/resnet50-19c8e357.pth'


# training settings
train:
  name: train
  engine_type: Trainer
  resume: " "
  optimizer:
    name: 'sgd' #adam,adamw,nadam,adamax,adadelta,adagrad,rmsprop,adabelif,nadamw,radam
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.9
  lr_schedular:
    name: 'cosine' #cosine,multistep,poly,tanh
    t_initial: 3
    lr_min: 0.00001
    k_decay: 1.0
    cycle_mul: 1.
    cycle_decay: 1.
    cycle_limit: 1.
    warmup_t: 0.
    warmup_lr_init: 0.000001
    noise_pct: 0.67
    noise_std: 1.0
    noise_seed: 42
  criterion:
    name: 'smooth' #bce,smooth,ce
    reduction: 'mean'

# validation settings
val:
  name: 'eval'
  engine_type: 'Evaluator'
  metric:
    name: 'topk'

#save checkpoint
save:

